-- Migration : entreprises GRD avec systeme parent_key
-- Meme structure que Type intervention / sous-types

-- 1. Migrer les anciennes listes 'Agents X' vers parent_key
UPDATE listes_parametres
SET parent_key = 'Entreprises::' || SUBSTRING(nom_liste FROM 8)
WHERE nom_liste LIKE 'Agents %' AND parent_key IS NULL;

-- 2. Inserer les entreprises GRD
INSERT INTO listes_parametres (nom_liste, valeur, ordre, parent_key) VALUES
  ('Entreprises', 'SICAE',               1,  NULL),
  ('Entreprises', 'Schneider Electric',  2,  NULL),
  ('Entreprises', 'INEO',                3,  NULL),
  ('Entreprises', 'Santerne',            4,  NULL),
  ('Entreprises', 'Pinson Paysage',      5,  NULL),
  ('Entreprises', 'ENERCON',             6,  NULL),
  ('Entreprises', 'VESTAS',              7,  NULL),
  ('Entreprises', 'Sofratel',            8,  NULL),
  ('Entreprises', 'Afludia',             9,  NULL),
  ('Entreprises', 'Energie Team',        10, NULL),
  ('Entreprises', 'H2AIR',              11, NULL),
  ('Entreprises', 'Enertrag',           12, NULL),
  ('Entreprises', 'Valemo',             13, NULL),
  ('Entreprises', '2SPB',               14, NULL),
  ('Entreprises', 'Serf of Life',       15, NULL),
  ('Entreprises', 'CERAN',              16, NULL),
  ('Entreprises', 'Eiffage',            17, NULL),
  ('Entreprises', 'CHUB',               18, NULL),
  ('Entreprises', 'Tesla (Megapack)',    19, NULL)
ON CONFLICT DO NOTHING;

-- 3. Listes de personnel (6 agents placeholder par entreprise)
INSERT INTO listes_parametres (nom_liste, valeur, ordre, parent_key) VALUES
  ('Personnel SICAE',              'Agent 1', 1, 'Entreprises::SICAE'),
  ('Personnel SICAE',              'Agent 2', 2, 'Entreprises::SICAE'),
  ('Personnel SICAE',              'Agent 3', 3, 'Entreprises::SICAE'),
  ('Personnel SICAE',              'Agent 4', 4, 'Entreprises::SICAE'),
  ('Personnel SICAE',              'Agent 5', 5, 'Entreprises::SICAE'),
  ('Personnel SICAE',              'Agent 6', 6, 'Entreprises::SICAE'),
  ('Personnel Schneider Electric', 'Agent 1', 1, 'Entreprises::Schneider Electric'),
  ('Personnel Schneider Electric', 'Agent 2', 2, 'Entreprises::Schneider Electric'),
  ('Personnel Schneider Electric', 'Agent 3', 3, 'Entreprises::Schneider Electric'),
  ('Personnel Schneider Electric', 'Agent 4', 4, 'Entreprises::Schneider Electric'),
  ('Personnel Schneider Electric', 'Agent 5', 5, 'Entreprises::Schneider Electric'),
  ('Personnel Schneider Electric', 'Agent 6', 6, 'Entreprises::Schneider Electric'),
  ('Personnel INEO',               'Agent 1', 1, 'Entreprises::INEO'),
  ('Personnel INEO',               'Agent 2', 2, 'Entreprises::INEO'),
  ('Personnel INEO',               'Agent 3', 3, 'Entreprises::INEO'),
  ('Personnel INEO',               'Agent 4', 4, 'Entreprises::INEO'),
  ('Personnel INEO',               'Agent 5', 5, 'Entreprises::INEO'),
  ('Personnel INEO',               'Agent 6', 6, 'Entreprises::INEO'),
  ('Personnel Santerne',           'Agent 1', 1, 'Entreprises::Santerne'),
  ('Personnel Santerne',           'Agent 2', 2, 'Entreprises::Santerne'),
  ('Personnel Santerne',           'Agent 3', 3, 'Entreprises::Santerne'),
  ('Personnel Santerne',           'Agent 4', 4, 'Entreprises::Santerne'),
  ('Personnel Santerne',           'Agent 5', 5, 'Entreprises::Santerne'),
  ('Personnel Santerne',           'Agent 6', 6, 'Entreprises::Santerne'),
  ('Personnel Pinson Paysage',     'Agent 1', 1, 'Entreprises::Pinson Paysage'),
  ('Personnel Pinson Paysage',     'Agent 2', 2, 'Entreprises::Pinson Paysage'),
  ('Personnel Pinson Paysage',     'Agent 3', 3, 'Entreprises::Pinson Paysage'),
  ('Personnel Pinson Paysage',     'Agent 4', 4, 'Entreprises::Pinson Paysage'),
  ('Personnel Pinson Paysage',     'Agent 5', 5, 'Entreprises::Pinson Paysage'),
  ('Personnel Pinson Paysage',     'Agent 6', 6, 'Entreprises::Pinson Paysage'),
  ('Personnel ENERCON',            'Agent 1', 1, 'Entreprises::ENERCON'),
  ('Personnel ENERCON',            'Agent 2', 2, 'Entreprises::ENERCON'),
  ('Personnel ENERCON',            'Agent 3', 3, 'Entreprises::ENERCON'),
  ('Personnel ENERCON',            'Agent 4', 4, 'Entreprises::ENERCON'),
  ('Personnel ENERCON',            'Agent 5', 5, 'Entreprises::ENERCON'),
  ('Personnel ENERCON',            'Agent 6', 6, 'Entreprises::ENERCON'),
  ('Personnel VESTAS',             'Agent 1', 1, 'Entreprises::VESTAS'),
  ('Personnel VESTAS',             'Agent 2', 2, 'Entreprises::VESTAS'),
  ('Personnel VESTAS',             'Agent 3', 3, 'Entreprises::VESTAS'),
  ('Personnel VESTAS',             'Agent 4', 4, 'Entreprises::VESTAS'),
  ('Personnel VESTAS',             'Agent 5', 5, 'Entreprises::VESTAS'),
  ('Personnel VESTAS',             'Agent 6', 6, 'Entreprises::VESTAS'),
  ('Personnel Sofratel',           'Agent 1', 1, 'Entreprises::Sofratel'),
  ('Personnel Sofratel',           'Agent 2', 2, 'Entreprises::Sofratel'),
  ('Personnel Sofratel',           'Agent 3', 3, 'Entreprises::Sofratel'),
  ('Personnel Sofratel',           'Agent 4', 4, 'Entreprises::Sofratel'),
  ('Personnel Sofratel',           'Agent 5', 5, 'Entreprises::Sofratel'),
  ('Personnel Sofratel',           'Agent 6', 6, 'Entreprises::Sofratel'),
  ('Personnel Afludia',            'Agent 1', 1, 'Entreprises::Afludia'),
  ('Personnel Afludia',            'Agent 2', 2, 'Entreprises::Afludia'),
  ('Personnel Afludia',            'Agent 3', 3, 'Entreprises::Afludia'),
  ('Personnel Afludia',            'Agent 4', 4, 'Entreprises::Afludia'),
  ('Personnel Afludia',            'Agent 5', 5, 'Entreprises::Afludia'),
  ('Personnel Afludia',            'Agent 6', 6, 'Entreprises::Afludia'),
  ('Personnel Energie Team',       'Agent 1', 1, 'Entreprises::Energie Team'),
  ('Personnel Energie Team',       'Agent 2', 2, 'Entreprises::Energie Team'),
  ('Personnel Energie Team',       'Agent 3', 3, 'Entreprises::Energie Team'),
  ('Personnel Energie Team',       'Agent 4', 4, 'Entreprises::Energie Team'),
  ('Personnel Energie Team',       'Agent 5', 5, 'Entreprises::Energie Team'),
  ('Personnel Energie Team',       'Agent 6', 6, 'Entreprises::Energie Team'),
  ('Personnel H2AIR',              'Agent 1', 1, 'Entreprises::H2AIR'),
  ('Personnel H2AIR',              'Agent 2', 2, 'Entreprises::H2AIR'),
  ('Personnel H2AIR',              'Agent 3', 3, 'Entreprises::H2AIR'),
  ('Personnel H2AIR',              'Agent 4', 4, 'Entreprises::H2AIR'),
  ('Personnel H2AIR',              'Agent 5', 5, 'Entreprises::H2AIR'),
  ('Personnel H2AIR',              'Agent 6', 6, 'Entreprises::H2AIR'),
  ('Personnel Enertrag',           'Agent 1', 1, 'Entreprises::Enertrag'),
  ('Personnel Enertrag',           'Agent 2', 2, 'Entreprises::Enertrag'),
  ('Personnel Enertrag',           'Agent 3', 3, 'Entreprises::Enertrag'),
  ('Personnel Enertrag',           'Agent 4', 4, 'Entreprises::Enertrag'),
  ('Personnel Enertrag',           'Agent 5', 5, 'Entreprises::Enertrag'),
  ('Personnel Enertrag',           'Agent 6', 6, 'Entreprises::Enertrag'),
  ('Personnel Valemo',             'Agent 1', 1, 'Entreprises::Valemo'),
  ('Personnel Valemo',             'Agent 2', 2, 'Entreprises::Valemo'),
  ('Personnel Valemo',             'Agent 3', 3, 'Entreprises::Valemo'),
  ('Personnel Valemo',             'Agent 4', 4, 'Entreprises::Valemo'),
  ('Personnel Valemo',             'Agent 5', 5, 'Entreprises::Valemo'),
  ('Personnel Valemo',             'Agent 6', 6, 'Entreprises::Valemo'),
  ('Personnel 2SPB',               'Agent 1', 1, 'Entreprises::2SPB'),
  ('Personnel 2SPB',               'Agent 2', 2, 'Entreprises::2SPB'),
  ('Personnel 2SPB',               'Agent 3', 3, 'Entreprises::2SPB'),
  ('Personnel 2SPB',               'Agent 4', 4, 'Entreprises::2SPB'),
  ('Personnel 2SPB',               'Agent 5', 5, 'Entreprises::2SPB'),
  ('Personnel 2SPB',               'Agent 6', 6, 'Entreprises::2SPB'),
  ('Personnel Serf of Life',       'Agent 1', 1, 'Entreprises::Serf of Life'),
  ('Personnel Serf of Life',       'Agent 2', 2, 'Entreprises::Serf of Life'),
  ('Personnel Serf of Life',       'Agent 3', 3, 'Entreprises::Serf of Life'),
  ('Personnel Serf of Life',       'Agent 4', 4, 'Entreprises::Serf of Life'),
  ('Personnel Serf of Life',       'Agent 5', 5, 'Entreprises::Serf of Life'),
  ('Personnel Serf of Life',       'Agent 6', 6, 'Entreprises::Serf of Life'),
  ('Personnel CERAN',              'Agent 1', 1, 'Entreprises::CERAN'),
  ('Personnel CERAN',              'Agent 2', 2, 'Entreprises::CERAN'),
  ('Personnel CERAN',              'Agent 3', 3, 'Entreprises::CERAN'),
  ('Personnel CERAN',              'Agent 4', 4, 'Entreprises::CERAN'),
  ('Personnel CERAN',              'Agent 5', 5, 'Entreprises::CERAN'),
  ('Personnel CERAN',              'Agent 6', 6, 'Entreprises::CERAN'),
  ('Personnel Eiffage',            'Agent 1', 1, 'Entreprises::Eiffage'),
  ('Personnel Eiffage',            'Agent 2', 2, 'Entreprises::Eiffage'),
  ('Personnel Eiffage',            'Agent 3', 3, 'Entreprises::Eiffage'),
  ('Personnel Eiffage',            'Agent 4', 4, 'Entreprises::Eiffage'),
  ('Personnel Eiffage',            'Agent 5', 5, 'Entreprises::Eiffage'),
  ('Personnel Eiffage',            'Agent 6', 6, 'Entreprises::Eiffage'),
  ('Personnel CHUB',               'Agent 1', 1, 'Entreprises::CHUB'),
  ('Personnel CHUB',               'Agent 2', 2, 'Entreprises::CHUB'),
  ('Personnel CHUB',               'Agent 3', 3, 'Entreprises::CHUB'),
  ('Personnel CHUB',               'Agent 4', 4, 'Entreprises::CHUB'),
  ('Personnel CHUB',               'Agent 5', 5, 'Entreprises::CHUB'),
  ('Personnel CHUB',               'Agent 6', 6, 'Entreprises::CHUB'),
  ('Personnel Tesla (Megapack)',    'Agent 1', 1, 'Entreprises::Tesla (Megapack)'),
  ('Personnel Tesla (Megapack)',    'Agent 2', 2, 'Entreprises::Tesla (Megapack)'),
  ('Personnel Tesla (Megapack)',    'Agent 3', 3, 'Entreprises::Tesla (Megapack)'),
  ('Personnel Tesla (Megapack)',    'Agent 4', 4, 'Entreprises::Tesla (Megapack)'),
  ('Personnel Tesla (Megapack)',    'Agent 5', 5, 'Entreprises::Tesla (Megapack)'),
  ('Personnel Tesla (Megapack)',    'Agent 6', 6, 'Entreprises::Tesla (Megapack)')
ON CONFLICT DO NOTHING;
